DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    email varchar,
    CONSTRAINT email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    available boolean,
    owner int REFERENCES users(id),
    request varchar
);

CREATE TABLE IF NOT EXISTS bookings (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start timestamp,
    ending timestamp,
    item_id int REFERENCES items(id),
    booker_id int REFERENCES users(id), --тот, кто бронирует
    status varchar DEFAULT 'WAITING'
);

CREATE TABLE IF NOT EXISTS comments (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar,
    item_id int REFERENCES items(id),
    author_id int REFERENCES users(id), --тот, кто бронирует
    created timestamp
);